spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: leak
    password: leak@apd2025
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      secret-key: "BeL3l2reIpmFMl+rWCtrYwgr/Ltf7uJWSegV2Mzd9N2ghrxukiiW93g="

  logging:
    level:
      org.springframework.security: DEBUG

server:
  port: 8092