spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: leak
    password: leak@apd2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      secret-key: "BeL3l2reIpmFMl+rWCtrYwgr/Ltf7uJWSegV2Mzd9N2ghrxukiiW93g="
      expiration-time: 3600000
      refresh-expiration-time: 604800000

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  logging:
    level:
      org.springframework.security: DEBUG


server:
  port: 8090

redis:
  host: ms_redis
  port: 6379

